architect:
  - h1alexbel
docker:
  image: l3r8y/rultor-image:1.0.3
merge:
  script: |
    mvn clean install -Pjacoco --errors -Dstyle.color=never
# @todo #1:45min Craft release script in rultor configuration.
#  We should create release script that will tag and release Java application
#  into GitHub releases page.
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9_]+)?$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean install -Prelease
deploy:
  script: |
    echo "There is no such thing as #deploy"
    exit -1
