name: 'code-review-action'
description: 'Quality of Code Review Checker'
author: 'Aliaksei Bialiauski <aliaksei.bialiauski@hey.com>'
branding:
  icon: 'arrow-down'
  color: 'gray-dark'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  openai_token:
    description: 'Open AI API key'
    required: true
  openai_model:
    description: 'Open AI API model'
    required: false
    default: 'gpt-4'
  deepinfra_token:
    description: 'Deep Infra API key'
    required: false
  deepinfra_model:
    description: 'Deep Infra API model'
    required: false
    default: 'Phind/Phind-CodeLlama-34B-v2'
  min_lines:
    description: 'Minimal amount of lines in the pull request to get analyzed by this action'
    required: false
    default: '0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.openai_token }}
    - ${{ inputs.openai_model }}
    - ${{ inputs.deepinfra_token }}
    - ${{ inputs.deepinfra_model }}
