---
name: Docker release
on:
  push:
    tags:
      - '*'
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean install -Prelease
      - name: Push to ghcr.io
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tracehubpm/code-review-action
          tags: ${{ github.ref_name }}, latest
          dockerfile: Dockerfile
          registry: ghcr.io
          username: tracehubpm
          password: ${{ secrets.GITHUB_TOKEN }}
