---
name: Docker release
on:
  push:
    tags:
      - '*'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean install -Prelease
      - name: Push to docker.io
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tracehub/code-review-action
          tags: ${{ github.ref_name }}, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: tracehub
          password: ${{ secrets.DOCKER_PASSWORD }}
